/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/comprovante-pagamento`; params?: Router.UnknownInputParams; } | { pathname: `/confirmacao-nome`; params?: Router.UnknownInputParams; } | { pathname: `/confirmacao-seguranca-1`; params?: Router.UnknownInputParams; } | { pathname: `/confirmacao-seguranca-2`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/inicio`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/pagamento-concluido`; params?: Router.UnknownInputParams; } | { pathname: `/pagamento-falhou`; params?: Router.UnknownInputParams; } | { pathname: `/pagamento`; params?: Router.UnknownInputParams; } | { pathname: `/pre-validacao`; params?: Router.UnknownInputParams; } | { pathname: `/qrcode-pix`; params?: Router.UnknownInputParams; } | { pathname: `/verificacao`; params?: Router.UnknownInputParams; } | { pathname: `/verificando-pagamento`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/admin`; params?: Router.UnknownOutputParams; } | { pathname: `/comprovante-pagamento`; params?: Router.UnknownOutputParams; } | { pathname: `/confirmacao-nome`; params?: Router.UnknownOutputParams; } | { pathname: `/confirmacao-seguranca-1`; params?: Router.UnknownOutputParams; } | { pathname: `/confirmacao-seguranca-2`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/inicio`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/pagamento-concluido`; params?: Router.UnknownOutputParams; } | { pathname: `/pagamento-falhou`; params?: Router.UnknownOutputParams; } | { pathname: `/pagamento`; params?: Router.UnknownOutputParams; } | { pathname: `/pre-validacao`; params?: Router.UnknownOutputParams; } | { pathname: `/qrcode-pix`; params?: Router.UnknownOutputParams; } | { pathname: `/verificacao`; params?: Router.UnknownOutputParams; } | { pathname: `/verificando-pagamento`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/admin${`?${string}` | `#${string}` | ''}` | `/comprovante-pagamento${`?${string}` | `#${string}` | ''}` | `/confirmacao-nome${`?${string}` | `#${string}` | ''}` | `/confirmacao-seguranca-1${`?${string}` | `#${string}` | ''}` | `/confirmacao-seguranca-2${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/inicio${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/pagamento-concluido${`?${string}` | `#${string}` | ''}` | `/pagamento-falhou${`?${string}` | `#${string}` | ''}` | `/pagamento${`?${string}` | `#${string}` | ''}` | `/pre-validacao${`?${string}` | `#${string}` | ''}` | `/qrcode-pix${`?${string}` | `#${string}` | ''}` | `/verificacao${`?${string}` | `#${string}` | ''}` | `/verificando-pagamento${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/admin`; params?: Router.UnknownInputParams; } | { pathname: `/comprovante-pagamento`; params?: Router.UnknownInputParams; } | { pathname: `/confirmacao-nome`; params?: Router.UnknownInputParams; } | { pathname: `/confirmacao-seguranca-1`; params?: Router.UnknownInputParams; } | { pathname: `/confirmacao-seguranca-2`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/inicio`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/pagamento-concluido`; params?: Router.UnknownInputParams; } | { pathname: `/pagamento-falhou`; params?: Router.UnknownInputParams; } | { pathname: `/pagamento`; params?: Router.UnknownInputParams; } | { pathname: `/pre-validacao`; params?: Router.UnknownInputParams; } | { pathname: `/qrcode-pix`; params?: Router.UnknownInputParams; } | { pathname: `/verificacao`; params?: Router.UnknownInputParams; } | { pathname: `/verificando-pagamento`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
